name: build

on:
    push:
        branches:
            - master

jobs:
    delete-artifacts:
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - uses: kolpav/purge-artifacts-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  expire-in: 10 minutes

    build:
        strategy:
            matrix:
                php: [ '7.3', '7.4' ]
                os: [ ubuntu-16.04, ubuntu-latest, windows-latest, macOS-latest ]

        runs-on: ${{ matrix.os }}
        name: php-${{ matrix.php }}-${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring, pcov
                  ini-values: memory_limit=2G
                  coverage: pcov

            - name: Validate composer
              run: composer validate

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run test suite
              if: "matrix.php != '7.4' || matrix.os != 'ubuntu-latest'"
              run: ./vendor/bin/phpunit

            - name: Run test suite (with coverage)
              if: "matrix.php == '7.4' && matrix.os == 'ubuntu-latest'"
              run: ./vendor/bin/phpunit --coverage-html=./coverage --coverage-clover ./coverage/coverage.xml

            - name: Compress artifacts
              if: "!contains(github.event.head_commit.message, '[no-test]') && matrix.php == '7.4' && matrix.os == 'ubuntu-latest'"
              uses: TonyBogdanov/zip@1.0
              with:
                  args: zip -qq -r ./coverage.zip ./coverage

            - name: Upload artifacts
              if: "!contains(github.event.head_commit.message, '[no-test]') && matrix.php == '7.4' && matrix.os == 'ubuntu-latest'"
              uses: actions/upload-artifact@v2
              with:
                  name: coverage
                  path: coverage.zip

    coverage:
        needs: [ build ]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Download artifacts
              uses: actions/download-artifact@v2
              with:
                  name: coverage

            - name: Decompress artifacts
              uses: TonyBogdanov/zip@1.0
              with:
                  args: unzip -qq ./coverage.zip -d ./

            - name: Build coverage
              uses: tonybogdanov/coverage@master
              with:
                  path: coverage

            - name: Publish coverage results
              uses: JamesIves/github-pages-deploy-action@3.4.9
              with:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: coverage
